// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1) {
  return window['go']['backend']['App']['CreateChat'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['backend']['App']['DeleteChat'](arg1);
}

export function GetChats() {
  return window['go']['backend']['App']['GetChats']();
}

export function GetMessages(arg1) {
  return window['go']['backend']['App']['GetMessages'](arg1);
}

export function GetModels() {
  return window['go']['backend']['App']['GetModels']();
}

export function PullModel(arg1) {
  return window['go']['backend']['App']['PullModel'](arg1);
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SendMessage'](arg1, arg2, arg3);
}
