// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateChat(arg1:string):Promise<string>;

export function DeleteChat(arg1:string):Promise<void>;

export function GetChats():Promise<Array<backend.Chat>>;

export function GetMessages(arg1:string):Promise<Array<backend.Message>>;

export function GetModels():Promise<Array<string>>;

export function PullModel(arg1:string):Promise<void>;

export function SaveMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:Array<backend.Message>):Promise<void>;
